/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.control;
import clases.validar;
import javax.swing.JOptionPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class barrio extends javax.swing.JFrame {

         /**
          * Creates new form barrio
          */
         public barrio() {
                  initComponents();
                  control.fillCombo(cb_ciudad, "select nomciud from ciudad");
                  control.fillTable2(jTable1, "select * from v_barrio");
                  setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                  setLocationRelativeTo(null);
         }

         /**
          * This method is called from within the constructor to
          * initialize the form. WARNING: Do NOT modify this code. The
          * content of this method is always regenerated by the Form
          * Editor.
          */
         @SuppressWarnings("unchecked")
         // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
         private void initComponents() {

                  jLabel1 = new javax.swing.JLabel();
                  jLabel2 = new javax.swing.JLabel();
                  txt_barrio = new javax.swing.JTextField();
                  cb_ciudad = new javax.swing.JComboBox<>();
                  jButton1 = new javax.swing.JButton();
                  jButton2 = new javax.swing.JButton();
                  jButton3 = new javax.swing.JButton();
                  jScrollPane1 = new javax.swing.JScrollPane();
                  jTable1 = new javax.swing.JTable();
                  jLabel3 = new javax.swing.JLabel();
                  buscar = new javax.swing.JTextField();

                  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                  jLabel1.setText("ciudad");

                  jLabel2.setText("barrio");

                  cb_ciudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                  jButton1.setText("ingresar");
                  jButton1.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jButton1ActionPerformed(evt);
                           }
                  });

                  jButton2.setText("actualizar");
                  jButton2.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jButton2ActionPerformed(evt);
                           }
                  });

                  jButton3.setText("elimnar");
                  jButton3.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jButton3ActionPerformed(evt);
                           }
                  });

                  jTable1.setModel(new javax.swing.table.DefaultTableModel(
                           new Object [][] {
                                    {null, null, null, null},
                                    {null, null, null, null},
                                    {null, null, null, null},
                                    {null, null, null, null}
                           },
                           new String [] {
                                    "Title 1", "Title 2", "Title 3", "Title 4"
                           }
                  ));
                  jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
                           public void mousePressed(java.awt.event.MouseEvent evt) {
                                    jTable1MousePressed(evt);
                           }
                  });
                  jScrollPane1.setViewportView(jTable1);

                  jLabel3.setText("ingresar barrios");

                  buscar.addKeyListener(new java.awt.event.KeyAdapter() {
                           public void keyTyped(java.awt.event.KeyEvent evt) {
                                    buscarKeyTyped(evt);
                           }
                  });

                  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                  getContentPane().setLayout(layout);
                  layout.setHorizontalGroup(
                           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addGroup(layout.createSequentialGroup()
                                                      .addGap(41, 41, 41)
                                                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                               .addGroup(layout.createSequentialGroup()
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                 .addComponent(jLabel2)
                                                                                 .addComponent(jLabel1))
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                 .addGroup(layout.createSequentialGroup()
                                                                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                          .addComponent(txt_barrio, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                          .addGap(48, 48, 48)
                                                                                          .addComponent(cb_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                               .addGroup(layout.createSequentialGroup()
                                                                        .addGap(4, 4, 4)
                                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(71, 71, 71)
                                                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                             .addGroup(layout.createSequentialGroup()
                                                      .addGap(227, 227, 227)
                                                      .addComponent(jLabel3))
                                             .addGroup(layout.createSequentialGroup()
                                                      .addGap(29, 29, 29)
                                                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
                                                               .addComponent(buscar))))
                                    .addContainerGap(21, Short.MAX_VALUE))
                  );
                  layout.setVerticalGroup(
                           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addGroup(layout.createSequentialGroup()
                                                      .addGap(35, 35, 35)
                                                      .addComponent(jLabel1)
                                                      .addGap(33, 33, 33))
                                             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                      .addContainerGap()
                                                      .addComponent(jLabel3)
                                                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                      .addComponent(cb_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addGap(18, 18, 18)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                             .addComponent(jLabel2)
                                             .addComponent(txt_barrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(77, 77, 77)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                             .addComponent(jButton1)
                                             .addComponent(jButton2)
                                             .addComponent(jButton3))
                                    .addGap(18, 18, 18)
                                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(20, Short.MAX_VALUE))
                  );

                  pack();
         }// </editor-fold>//GEN-END:initComponents

         private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                  // TODO add your handling code here:
                  if (txt_barrio.getText().trim().length() != 0) {
                           if (cb_ciudad.getSelectedIndex() != -1) {

                                    String sql = String.format("insert into barrio values(null,'%s',(select idciudad from ciudad where nomciud='%s'))",
                                            txt_barrio.getText().trim(), cb_ciudad.getSelectedItem().toString());
                                    if (control.update(sql) > 0) {
                                             JOptionPane.showMessageDialog(null, "se ingreso");
                                             control.fillTable2(jTable1, "select * from v_barrio");
                                    } else {
                                             JOptionPane.showMessageDialog(null, "no  se ingreso");
                                    }

                           } else {
                                    JOptionPane.showMessageDialog(null, "seleccione el combo");

                           }

                  } else {
                           JOptionPane.showMessageDialog(null, "llene el campo barrio");
                  }
         }//GEN-LAST:event_jButton1ActionPerformed

         private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                  // TODO add your handling code here:

                  if (jTable1.getSelectedRowCount() > 0) {
                           if (txt_barrio.getText().trim().length() != 0) {
                                    if (cb_ciudad.getSelectedIndex() != -1) {

                                             String sql = String.format("update barrio set nombarrio='%s' , idciudad=(select idCiudad from ciudad  where nomciud ='%s') where idbarrio=%s",
                                                     txt_barrio.getText().trim(), cb_ciudad.getSelectedItem().toString(), jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                                             if (control.update(sql) > 0) {
                                                      JOptionPane.showMessageDialog(null, "se actualizo correctamente");
                                                      control.fillTable2(jTable1, "select * from v_barrio");
                                             }
                                    } else {

                                             JOptionPane.showMessageDialog(null, "seleccione el combo");
                                    }
                           } else {
                                    JOptionPane.showMessageDialog(null, "llene el campo barrio");
                           }
                  } else {
                           JOptionPane.showMessageDialog(null, "seleccione la tabla primero");
                  }
         }//GEN-LAST:event_jButton2ActionPerformed

         private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
                  // TODO add your handling code here:

                  cb_ciudad.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
                  txt_barrio.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
         }//GEN-LAST:event_jTable1MousePressed

         private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                  // TODO add your handling code here:
                  if (jTable1.getSelectedRowCount() > 0) {
                           String sql = String.format("delete from barrio where idbarrio =%s", jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                           if (control.update(sql) > 0) {
                                    control.fillTable2(jTable1, "select * from v_barrio");
                                    JOptionPane.showMessageDialog(null, "se borro correctamente");
                           }
                  } else {
                           JOptionPane.showMessageDialog(null, "seleccione la tabla primero");
                  }
         }//GEN-LAST:event_jButton3ActionPerformed

         private void buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyTyped
                  // TODO add your handling code here:

                  int pos = buscar.getCaretPosition();
                  String parametro = (buscar.getText().substring(0, pos) + evt.getKeyChar() + buscar.getText().substring(pos)).trim();

                  if (parametro.trim().length() == 0) {
                           control.fillTable2(jTable1, "select * from v_barrio");

                  } else {

                           String sql = "select * from v_barrio where barrio like '%" + parametro + "%' or ciudad like '%" + parametro + "%'";
                           control.fillTable2(jTable1, sql);

                  }
         }//GEN-LAST:event_buscarKeyTyped

         /**
          * @param args the command line arguments
          */
         public static void main(String args[]) {
                  /* Set the Nimbus look and feel */
                  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                  /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                   */
                  try {
                           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                    if ("Nimbus".equals(info.getName())) {
                                             javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                             break;
                                    }
                           }
                  } catch (ClassNotFoundException ex) {
                           java.util.logging.Logger.getLogger(barrio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  } catch (InstantiationException ex) {
                           java.util.logging.Logger.getLogger(barrio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  } catch (IllegalAccessException ex) {
                           java.util.logging.Logger.getLogger(barrio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                           java.util.logging.Logger.getLogger(barrio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  }
                  //</editor-fold>

                  /* Create and display the form */
                  java.awt.EventQueue.invokeLater(new Runnable() {
                           public void run() {
                                    new barrio().setVisible(true);
                           }
                  });
         }

         // Variables declaration - do not modify//GEN-BEGIN:variables
         private javax.swing.JTextField buscar;
         private javax.swing.JComboBox<String> cb_ciudad;
         private javax.swing.JButton jButton1;
         private javax.swing.JButton jButton2;
         private javax.swing.JButton jButton3;
         private javax.swing.JLabel jLabel1;
         private javax.swing.JLabel jLabel2;
         private javax.swing.JLabel jLabel3;
         private javax.swing.JScrollPane jScrollPane1;
         private javax.swing.JTable jTable1;
         private javax.swing.JTextField txt_barrio;
         // End of variables declaration//GEN-END:variables
}
