/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.control;
import clases.validar;
import javax.swing.JOptionPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class ciudadanos extends javax.swing.JFrame {

         /**
          * Creates new form cuidadanos
          */
         public ciudadanos() {
                  initComponents();
                  control.fillTable2(tabla, "select * from v_ciudadano");
                  control.fillCombo(cb_barrio, "select barrio from v_barrio");
                  cb_genero.removeAllItems();
                  cb_genero.addItem("masculino");
                  cb_genero.addItem("femenino");
                  
                    setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    setLocationRelativeTo(null);
         }

         /**
          * This method is called from within the constructor to
          * initialize the form. WARNING: Do NOT modify this code. The
          * content of this method is always regenerated by the Form
          * Editor.
          */
         @SuppressWarnings("unchecked")
         // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
         private void initComponents() {

                  jPanel1 = new javax.swing.JPanel();
                  jLabel1 = new javax.swing.JLabel();
                  txt_dni = new javax.swing.JTextField();
                  jLabel3 = new javax.swing.JLabel();
                  jLabel4 = new javax.swing.JLabel();
                  jLabel5 = new javax.swing.JLabel();
                  txt_nombre = new javax.swing.JTextField();
                  cb_barrio = new javax.swing.JComboBox<>();
                  txt_apell = new javax.swing.JTextField();
                  cb_genero = new javax.swing.JComboBox<>();
                  jLabel7 = new javax.swing.JLabel();
                  txt_dir = new javax.swing.JTextField();
                  jLabel8 = new javax.swing.JLabel();
                  jButton1 = new javax.swing.JButton();
                  jButton2 = new javax.swing.JButton();
                  jButton3 = new javax.swing.JButton();
                  jButton4 = new javax.swing.JButton();
                  jScrollPane1 = new javax.swing.JScrollPane();
                  tabla = new javax.swing.JTable();

                  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                  getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                  jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                  jLabel1.setText("dni");
                  jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, -1, -1));

                  txt_dni.setName("dni"); // NOI18N
                  txt_dni.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    txt_dniActionPerformed(evt);
                           }
                  });
                  txt_dni.addKeyListener(new java.awt.event.KeyAdapter() {
                           public void keyTyped(java.awt.event.KeyEvent evt) {
                                    txt_dniKeyTyped(evt);
                           }
                  });
                  jPanel1.add(txt_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 6, 188, -1));

                  jLabel3.setText("nombre");
                  jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 58, -1, -1));

                  jLabel4.setText("epellido");
                  jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 88, -1, -1));

                  jLabel5.setText("direccion");
                  jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 134, -1, -1));

                  txt_nombre.setName("nombre"); // NOI18N
                  jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 180, -1));

                  cb_barrio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                  cb_barrio.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    cb_barrioActionPerformed(evt);
                           }
                  });
                  jPanel1.add(cb_barrio, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 240, -1));

                  txt_apell.setName("apellido"); // NOI18N
                  jPanel1.add(txt_apell, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 180, -1));

                  cb_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                  jPanel1.add(cb_genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 240, -1));

                  jLabel7.setText("genero");
                  jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

                  txt_dir.setName("direccion"); // NOI18N
                  jPanel1.add(txt_dir, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 180, -1));

                  jLabel8.setText("barrio");
                  jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

                  getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 19, 730, 180));

                  jButton1.setText("agregar");
                  jButton1.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jButton1ActionPerformed(evt);
                           }
                  });
                  getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

                  jButton2.setText("actualizar");
                  getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

                  jButton3.setText("eliminar");
                  jButton3.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jButton3ActionPerformed(evt);
                           }
                  });
                  getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

                  jButton4.setText("cancelar");
                  getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

                  tabla.setModel(new javax.swing.table.DefaultTableModel(
                           new Object [][] {
                                    {null, null, null, null},
                                    {null, null, null, null},
                                    {null, null, null, null},
                                    {null, null, null, null}
                           },
                           new String [] {
                                    "Title 1", "Title 2", "Title 3", "Title 4"
                           }
                  ));
                  jScrollPane1.setViewportView(tabla);

                  getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 700, 270));

                  pack();
         }// </editor-fold>//GEN-END:initComponents

         private void cb_barrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_barrioActionPerformed
                  // TODO add your handling code here:
         }//GEN-LAST:event_cb_barrioActionPerformed

         private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                  // TODO add your handling code here:

                  if (!validar.esCajaVacio(txt_apell, txt_dni, txt_nombre)) {
                           if (cb_barrio.getSelectedIndex() != -1 && cb_genero.getSelectedIndex() != -1) {

                                    if (txt_dni.getText().trim().length() == 8) {
                                             String sql = String.format("call ingresar_ciudadano('%s','%s','%s','%s','%s','%s')",
                                                     txt_dni.getText().trim(), txt_nombre.getText().trim(), txt_apell.getText().trim(),
                                                     txt_dir.getText().trim(), cb_genero.getSelectedItem().toString(),
                                                     cb_barrio.getSelectedItem().toString());

                                             control.update(sql);
                                             control.fillTable2(tabla, "select * from v_ciudadano");
                                    } else {
                                             JOptionPane.showMessageDialog(null, "el dni solo es de 8 dijitos");
                                    }
                           } else {
                                    JOptionPane.showMessageDialog(null, "seleccione los combos");
                           }

                  } else {

                  }
         }//GEN-LAST:event_jButton1ActionPerformed

         private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                  // TODO add your handling code here:
         }//GEN-LAST:event_jButton3ActionPerformed

         private void txt_dniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dniActionPerformed
                  // TODO add your handling code here:
         }//GEN-LAST:event_txt_dniActionPerformed

         private void txt_dniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dniKeyTyped
                  // TODO add your handling code here:
                  if ((evt.getKeyChar() < 48) || (evt.getKeyChar() > 57) || txt_dni.getText().trim().length() > 7) {

                           evt.consume();

                  }

         }//GEN-LAST:event_txt_dniKeyTyped

         /**
          * @param args the command line arguments
          */
         public static void main(String args[]) {
                  /* Set the Nimbus look and feel */
                  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                  /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                   */
                  try {
                           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                    if ("Nimbus".equals(info.getName())) {
                                             javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                             break;
                                    }
                           }
                  } catch (ClassNotFoundException ex) {
                           java.util.logging.Logger.getLogger(ciudadanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  } catch (InstantiationException ex) {
                           java.util.logging.Logger.getLogger(ciudadanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  } catch (IllegalAccessException ex) {
                           java.util.logging.Logger.getLogger(ciudadanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                           java.util.logging.Logger.getLogger(ciudadanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  }
                  //</editor-fold>
                  //</editor-fold>

                  /* Create and display the form */
                  java.awt.EventQueue.invokeLater(new Runnable() {
                           public void run() {
                                    new ciudadanos().setVisible(true);
                           }
                  });
         }

         // Variables declaration - do not modify//GEN-BEGIN:variables
         private javax.swing.JComboBox<String> cb_barrio;
         private javax.swing.JComboBox<String> cb_genero;
         private javax.swing.JButton jButton1;
         private javax.swing.JButton jButton2;
         private javax.swing.JButton jButton3;
         private javax.swing.JButton jButton4;
         private javax.swing.JLabel jLabel1;
         private javax.swing.JLabel jLabel3;
         private javax.swing.JLabel jLabel4;
         private javax.swing.JLabel jLabel5;
         private javax.swing.JLabel jLabel7;
         private javax.swing.JLabel jLabel8;
         private javax.swing.JPanel jPanel1;
         private javax.swing.JScrollPane jScrollPane1;
         private javax.swing.JTable tabla;
         private javax.swing.JTextField txt_apell;
         private javax.swing.JTextField txt_dir;
         private javax.swing.JTextField txt_dni;
         private javax.swing.JTextField txt_nombre;
         // End of variables declaration//GEN-END:variables
}
