/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.control;
import clases.validar;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import jxl.biff.drawing.ComboBox;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class evaluacion extends javax.swing.JFrame {

         String usuario_id = "1";
         DefaultTableModel modelo = new DefaultTableModel();

         /**
          * Creates new form evaluacion
          */
         public evaluacion() {
                  initComponents();
                  control.fillTable2(tabla1, "select * from v_ciudadano");
                  control.fillCombo(cb_criterio, "select nomcrite from criterio;");

                  modelo.addColumn("criterio");
                  modelo.addColumn("valor");
                  tabla2.setModel(modelo);
                  ((JSpinner.DefaultEditor) rango.getEditor()).getTextField().setEditable(false);
                  
                    setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    setLocationRelativeTo(null);
         }

         public evaluacion(String usuario_id) {
                  initComponents();
                  control.fillTable2(tabla1, "select * from v_ciudadano");
                  control.fillCombo(cb_criterio, "select nomcrite from criterio;");

                  modelo.addColumn("criterio");
                  modelo.addColumn("valor");
                  tabla2.setModel(modelo);

                  this.usuario_id = usuario_id;

                  ((JSpinner.DefaultEditor) rango.getEditor()).getTextField().setEditable(false);
                  
                    setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    setLocationRelativeTo(null);
         }

         /**
          * This method is called from within the constructor to
          * initialize the form. WARNING: Do NOT modify this code. The
          * content of this method is always regenerated by the Form
          * Editor.
          */
         @SuppressWarnings("unchecked")
         // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
         private void initComponents() {

                  jScrollPane1 = new javax.swing.JScrollPane();
                  tabla1 = new javax.swing.JTable();
                  rango = new javax.swing.JSpinner();
                  jLabel2 = new javax.swing.JLabel();
                  cb_criterio = new javax.swing.JComboBox<>();
                  jLabel3 = new javax.swing.JLabel();
                  jScrollPane2 = new javax.swing.JScrollPane();
                  tabla2 = new javax.swing.JTable();
                  jButton1 = new javax.swing.JButton();
                  jLabel4 = new javax.swing.JLabel();
                  buscar = new javax.swing.JTextField();
                  jButton2 = new javax.swing.JButton();
                  lb_info = new javax.swing.JLabel();
                  jLabel1 = new javax.swing.JLabel();
                  total = new javax.swing.JLabel();
                  jScrollPane3 = new javax.swing.JScrollPane();
                  jTextArea1 = new javax.swing.JTextArea();
                  jLabel5 = new javax.swing.JLabel();
                  jButton3 = new javax.swing.JButton();
                  jLabel6 = new javax.swing.JLabel();
                  cb_vulnerable = new javax.swing.JComboBox<>();
                  jSeparator1 = new javax.swing.JSeparator();

                  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                  getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                  tabla1.setModel(new javax.swing.table.DefaultTableModel(
                           new Object [][] {
                                    {null, null, null, null},
                                    {null, null, null, null},
                                    {null, null, null, null},
                                    {null, null, null, null}
                           },
                           new String [] {
                                    "Title 1", "Title 2", "Title 3", "Title 4"
                           }
                  ));
                  tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
                           public void mousePressed(java.awt.event.MouseEvent evt) {
                                    tabla1MousePressed(evt);
                           }
                  });
                  jScrollPane1.setViewportView(tabla1);

                  getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 77, 1050, 115));

                  rango.addKeyListener(new java.awt.event.KeyAdapter() {
                           public void keyTyped(java.awt.event.KeyEvent evt) {
                                    rangoKeyTyped(evt);
                           }
                  });
                  getContentPane().add(rango, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 58, -1));

                  jLabel2.setText("condicion a evaluar");
                  getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

                  cb_criterio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                  cb_criterio.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    cb_criterioActionPerformed(evt);
                           }
                  });
                  getContentPane().add(cb_criterio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 152, -1));

                  jLabel3.setText("valor");
                  getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 44, -1));

                  tabla2.setModel(new javax.swing.table.DefaultTableModel(
                           new Object [][] {
                                    {null, null, null, null},
                                    {null, null, null, null},
                                    {null, null, null, null},
                                    {null, null, null, null}
                           },
                           new String [] {
                                    "Title 1", "Title 2", "Title 3", "Title 4"
                           }
                  ));
                  jScrollPane2.setViewportView(tabla2);

                  getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 650, 100));

                  jButton1.setText("agregar");
                  jButton1.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jButton1ActionPerformed(evt);
                           }
                  });
                  getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 77, -1));

                  jLabel4.setText("buscar ciudadano");
                  getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 47, -1, -1));

                  buscar.addKeyListener(new java.awt.event.KeyAdapter() {
                           public void keyTyped(java.awt.event.KeyEvent evt) {
                                    buscarKeyTyped(evt);
                           }
                  });
                  getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 43, 870, -1));

                  jButton2.setText("grabar evaluacion");
                  jButton2.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jButton2ActionPerformed(evt);
                           }
                  });
                  getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 560, 260, 60));

                  lb_info.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                  lb_info.setText("no se ha seleccionado");
                  getContentPane().add(lb_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 290, -1));

                  jLabel1.setText("puntaje totas de vulnerabilidad : ");
                  getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

                  total.setText("0");
                  getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 40, -1));

                  jTextArea1.setColumns(20);
                  jTextArea1.setRows(5);
                  jScrollPane3.setViewportView(jTextArea1);

                  getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 290, 100));

                  jLabel5.setText("observaciones");
                  getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, -1));

                  jButton3.setText("limpiar tabla");
                  jButton3.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jButton3ActionPerformed(evt);
                           }
                  });
                  getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, -1, -1));

                  jLabel6.setText("¿se considera vulnerable?");
                  getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, -1, -1));

                  cb_vulnerable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "si", "no" }));
                  getContentPane().add(cb_vulnerable, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 220, -1));

                  jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
                  getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 30, 150));

                  pack();
         }// </editor-fold>//GEN-END:initComponents
public int hallarV() {
                  int cant = 0;
                  for (int i = 0; i < tabla2.getRowCount(); i++) {
                           cant += Integer.parseInt(tabla2.getValueAt(i, 1).toString());

                  }
                  return cant;
         }

         private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                  // TODO add your handling code here:
                  if (tabla1.getSelectedRowCount() == 1) {
                           if (cb_criterio.getSelectedIndex() != -1) {
                                    if (!validar.buscarDatoEnJTable(tabla2, cb_criterio.getSelectedItem().toString(), 0)) {

                                             String[] datos = {
                                                      cb_criterio.getSelectedItem().toString(),
                                                      rango.getValue().toString()};
                                             modelo.addRow(datos);
                                             total.setText(hallarV() + "");
                                    } else {
                                             JOptionPane.showMessageDialog(null, "ya se encuentra añadido");
                                    }

                           } else {
                                    JOptionPane.showMessageDialog(null, "seleccione la condicion");
                           }

                  } else {
                           JOptionPane.showMessageDialog(null, "seleccione el alumno");
                  }
         }//GEN-LAST:event_jButton1ActionPerformed

         private void cb_criterioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_criterioActionPerformed
                  // TODO add your handling code here:

                  if (cb_criterio.getSelectedIndex() != -1) {
                           ResultSet r = control.returnResultset("select * from criterio where nomcrite='" + cb_criterio.getSelectedItem().toString() + "'");

                           int min = 0;
                           int max = 0;

                           try {
                                    if (r.next()) {
                                             min = r.getInt(3);
                                             max = r.getInt(4);

                                    }

                                    rango.setModel(new SpinnerNumberModel(min, min, max, 1));
                           } catch (SQLException ex) {
                                    Logger.getLogger(evaluacion.class.getName()).log(Level.SEVERE, null, ex);
                           }
                  }
         }//GEN-LAST:event_cb_criterioActionPerformed

         private void rangoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rangoKeyTyped
                  // TODO add your handling code here:

         }//GEN-LAST:event_rangoKeyTyped

         private void buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyTyped
                  // TODO add your handling code here:
                  int pos = buscar.getCaretPosition();
                  String parametro = (buscar.getText().substring(0, pos) + evt.getKeyChar() + buscar.getText().substring(pos)).trim();

                  if (parametro.trim().length() == 0) {
                           control.fillTable2(tabla1, "select * from v_ciudadano");
                  } else {

                           String sql = "select * from v_ciudadano where nombre like '%"
                                   + parametro + "%' or dni like '%" + parametro + "%' or apellido like '%" + parametro + "%'";
                           control.fillTable2(tabla1, sql);

                  }
         }//GEN-LAST:event_buscarKeyTyped

         private void tabla1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla1MousePressed
                  lb_info.setText(tabla1.getValueAt(tabla1.getSelectedRow(), 2).toString() + "  "
                          + tabla1.getValueAt(tabla1.getSelectedRow(), 3).toString());

                  control.limTable(modelo);
                  total.setText("0");
         }//GEN-LAST:event_tabla1MousePressed

         private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                  // TODO add your handling code here:
                  int vul = 0;
                  if (cb_vulnerable.getSelectedItem().toString().equalsIgnoreCase("si")) {
                           vul = 1;
                  } else {
                           vul = 0;
                  }

                  if (tabla2.getRowCount() != 0) {
                           if (!control.checkQuery("select * from valorvulnerabilidad  as v inner join evaluacion  as e on v.idValorVulnerabilidad=e.idValorVulnerabilidad where idCiudadano="
                                   + tabla1.getValueAt(tabla1.getSelectedRow(), 0))) {
                                    String ciudadano_id = tabla1.getValueAt(tabla1.getSelectedRow(), 0).toString();
                                    String obser = jTextArea1.getText();

                                    String sql = String.format("insert into valorvulnerabilidad values(null,%s)", hallarV());
                                    control.update(sql);

                                    String valorVul_id = control.returnData("select idValorVulnerabilidad from valorvulnerabilidad order by idValorVulnerabilidad desc limit 1");

                                    sql = String.format("insert into evaluacion values(null,curdate(),curtime(),'%s' ,'%s',%s,%s,%s)",
                                            jTextArea1.getText(), ciudadano_id, usuario_id, valorVul_id,vul);
                                    System.out.println(sql);
                                    control.update(sql);
                                    String eval_id = control.returnData("select * from evaluacion order by idevaluacion desc limit 1 ");
                                    insertarDetalleEval(eval_id);
                           } else {
                                    JOptionPane.showMessageDialog(null, "el alumno ya a sido evaluado con anterioridad");
                           }

                           control.limTable(modelo);
                  } else {
                           JOptionPane.showMessageDialog(null, "no hay nada para grabar");
                  }

         }//GEN-LAST:event_jButton2ActionPerformed

         private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                  // TODO add your handling code here:
                  total.setText("0");
                  control.limTable(modelo);
         }//GEN-LAST:event_jButton3ActionPerformed
         public void insertarDetalleEval(String evaluacion_id) {
                  for (int i = 0; i < tabla2.getRowCount(); i++) {
                           String sql = String.format(" select idcriterio from criterio where nomcrite='%s'", tabla2.getValueAt(i, 0));
                           String criterio_id = control.returnData(sql);

                           sql = String.format("insert into detalleevaluacion values(null,%s,%s,%s);",
                                   tabla2.getValueAt(i, 1).toString(), criterio_id, evaluacion_id);
                           control.update(sql);
                  }
         }

         /**
          * @param args the command line arguments
          */
         public static void main(String args[]) {
                  /* Set the Nimbus look and feel */
                  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                  /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                   */
                  try {
                           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                    if ("Nimbus".equals(info.getName())) {
                                             javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                             break;
                                    }
                           }
                  } catch (ClassNotFoundException ex) {
                           java.util.logging.Logger.getLogger(evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  } catch (InstantiationException ex) {
                           java.util.logging.Logger.getLogger(evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  } catch (IllegalAccessException ex) {
                           java.util.logging.Logger.getLogger(evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                           java.util.logging.Logger.getLogger(evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  }
                  //</editor-fold>

                  /* Create and display the form */
                  java.awt.EventQueue.invokeLater(new Runnable() {
                           public void run() {
                                    new evaluacion().setVisible(true);
                           }
                  });
         }

         // Variables declaration - do not modify//GEN-BEGIN:variables
         private javax.swing.JTextField buscar;
         private javax.swing.JComboBox<String> cb_criterio;
         private javax.swing.JComboBox<String> cb_vulnerable;
         private javax.swing.JButton jButton1;
         private javax.swing.JButton jButton2;
         private javax.swing.JButton jButton3;
         private javax.swing.JLabel jLabel1;
         private javax.swing.JLabel jLabel2;
         private javax.swing.JLabel jLabel3;
         private javax.swing.JLabel jLabel4;
         private javax.swing.JLabel jLabel5;
         private javax.swing.JLabel jLabel6;
         private javax.swing.JScrollPane jScrollPane1;
         private javax.swing.JScrollPane jScrollPane2;
         private javax.swing.JScrollPane jScrollPane3;
         private javax.swing.JSeparator jSeparator1;
         private javax.swing.JTextArea jTextArea1;
         private javax.swing.JLabel lb_info;
         private javax.swing.JSpinner rango;
         private javax.swing.JTable tabla1;
         private javax.swing.JTable tabla2;
         private javax.swing.JLabel total;
         // End of variables declaration//GEN-END:variables
}
