/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.control;
import clases.validar;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import jxl.biff.drawing.ComboBox;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class evaluacion extends javax.swing.JFrame {

         DefaultTableModel modelo = new DefaultTableModel();

         /**
          * Creates new form evaluacion
          */
         public evaluacion() {
                  initComponents();
                  control.fillTable2(tabla1, "select * from v_ciudadano");
                  control.fillCombo(cb_criterio, "select nomcrite from criterio;");

                  modelo.addColumn("idciudadano");
                  modelo.addColumn("nombre");
                  modelo.addColumn("apellido");
                  modelo.addColumn("criterio");
                  modelo.addColumn("valor");
                  tabla2.setModel(modelo);
         }

         /**
          * This method is called from within the constructor to
          * initialize the form. WARNING: Do NOT modify this code. The
          * content of this method is always regenerated by the Form
          * Editor.
          */
         @SuppressWarnings("unchecked")
         // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
         private void initComponents() {

                  jScrollPane1 = new javax.swing.JScrollPane();
                  tabla1 = new javax.swing.JTable();
                  jLabel1 = new javax.swing.JLabel();
                  rango = new javax.swing.JSpinner();
                  jLabel2 = new javax.swing.JLabel();
                  cb_criterio = new javax.swing.JComboBox<>();
                  jLabel3 = new javax.swing.JLabel();
                  jScrollPane2 = new javax.swing.JScrollPane();
                  tabla2 = new javax.swing.JTable();
                  jButton1 = new javax.swing.JButton();

                  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                  tabla1.setModel(new javax.swing.table.DefaultTableModel(
                           new Object [][] {
                                    {null, null, null, null},
                                    {null, null, null, null},
                                    {null, null, null, null},
                                    {null, null, null, null}
                           },
                           new String [] {
                                    "Title 1", "Title 2", "Title 3", "Title 4"
                           }
                  ));
                  jScrollPane1.setViewportView(tabla1);

                  jLabel1.setText("ciudadano");

                  rango.addKeyListener(new java.awt.event.KeyAdapter() {
                           public void keyTyped(java.awt.event.KeyEvent evt) {
                                    rangoKeyTyped(evt);
                           }
                  });

                  jLabel2.setText("condicion a evaluar");

                  cb_criterio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                  cb_criterio.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    cb_criterioActionPerformed(evt);
                           }
                  });

                  jLabel3.setText("valor");

                  tabla2.setModel(new javax.swing.table.DefaultTableModel(
                           new Object [][] {
                                    {null, null, null, null},
                                    {null, null, null, null},
                                    {null, null, null, null},
                                    {null, null, null, null}
                           },
                           new String [] {
                                    "Title 1", "Title 2", "Title 3", "Title 4"
                           }
                  ));
                  jScrollPane2.setViewportView(tabla2);

                  jButton1.setText("agregar");
                  jButton1.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jButton1ActionPerformed(evt);
                           }
                  });

                  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                  getContentPane().setLayout(layout);
                  layout.setHorizontalGroup(
                           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addGroup(layout.createSequentialGroup()
                                                      .addGap(98, 98, 98)
                                                      .addComponent(jLabel1))
                                             .addGroup(layout.createSequentialGroup()
                                                      .addContainerGap()
                                                      .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE))
                                             .addGroup(layout.createSequentialGroup()
                                                      .addGap(35, 35, 35)
                                                      .addComponent(jLabel2)
                                                      .addGap(18, 18, 18)
                                                      .addComponent(cb_criterio, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addGap(42, 42, 42)
                                                      .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                      .addComponent(rango, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                             .addGroup(layout.createSequentialGroup()
                                                      .addGap(102, 102, 102)
                                                      .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addContainerGap(50, Short.MAX_VALUE))
                           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(171, 171, 171))
                  );
                  layout.setVerticalGroup(
                           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                             .addComponent(jLabel2)
                                             .addComponent(cb_criterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(jLabel3)
                                             .addComponent(rango, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(2, 2, 2)
                                    .addComponent(jButton1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(210, 210, 210))
                  );

                  pack();
         }// </editor-fold>//GEN-END:initComponents

         private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                  // TODO add your handling code here:
                  if (tabla1.getSelectedRowCount() == 1) {
                           if (cb_criterio.getSelectedIndex() != -1) {
                                    if (!validar.buscarDatoEnJTable(tabla2, cb_criterio.getSelectedItem().toString(), 3)) {
                                             
                                             String []datos={tabla1.getValueAt(tabla1.getSelectedRow(), 0).toString()};
                                            
                                    } else {
                                             JOptionPane.showMessageDialog(null, "ya se encuentra añadido");
                                    }

                           } else {
                                    JOptionPane.showMessageDialog(null, "seleccione la condicion");
                           }

                  } else {
                           JOptionPane.showMessageDialog(null, "seleccione el alumno");
                  }
         }//GEN-LAST:event_jButton1ActionPerformed

         private void cb_criterioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_criterioActionPerformed
                  // TODO add your handling code here:

                  if (cb_criterio.getSelectedIndex() != -1) {
                           ResultSet r = control.returnResultset("select * from criterio where nomcrite='" + cb_criterio.getSelectedItem().toString() + "'");

                           int min = 0;
                           int max = 0;

                           try {
                                    if (r.next()) {
                                             min = r.getInt(3);
                                             max = r.getInt(4);

                                    }

                                    rango.setModel(new SpinnerNumberModel(0, min, max, 1));
                           } catch (SQLException ex) {
                                    Logger.getLogger(evaluacion.class.getName()).log(Level.SEVERE, null, ex);
                           }
                  }
         }//GEN-LAST:event_cb_criterioActionPerformed

         private void rangoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rangoKeyTyped
                  // TODO add your handling code here:

         }//GEN-LAST:event_rangoKeyTyped

         /**
          * @param args the command line arguments
          */
         public static void main(String args[]) {
                  /* Set the Nimbus look and feel */
                  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                  /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                   */
                  try {
                           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                    if ("Nimbus".equals(info.getName())) {
                                             javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                             break;
                                    }
                           }
                  } catch (ClassNotFoundException ex) {
                           java.util.logging.Logger.getLogger(evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  } catch (InstantiationException ex) {
                           java.util.logging.Logger.getLogger(evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  } catch (IllegalAccessException ex) {
                           java.util.logging.Logger.getLogger(evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                           java.util.logging.Logger.getLogger(evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  }
                  //</editor-fold>

                  /* Create and display the form */
                  java.awt.EventQueue.invokeLater(new Runnable() {
                           public void run() {
                                    new evaluacion().setVisible(true);
                           }
                  });
         }

         // Variables declaration - do not modify//GEN-BEGIN:variables
         private javax.swing.JComboBox<String> cb_criterio;
         private javax.swing.JButton jButton1;
         private javax.swing.JLabel jLabel1;
         private javax.swing.JLabel jLabel2;
         private javax.swing.JLabel jLabel3;
         private javax.swing.JScrollPane jScrollPane1;
         private javax.swing.JScrollPane jScrollPane2;
         private javax.swing.JSpinner rango;
         private javax.swing.JTable tabla1;
         private javax.swing.JTable tabla2;
         // End of variables declaration//GEN-END:variables
}
