/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.control;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class reporte extends javax.swing.JFrame {

         /**
          * Creates new form reporte
          */
         public reporte() {
                  initComponents();

                  control.fillCombo(ciudad, "select nomciud from ciudad");
                  
                   setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                  setLocationRelativeTo(null);
         }

         /**
          * This method is called from within the constructor to
          * initialize the form. WARNING: Do NOT modify this code. The
          * content of this method is always regenerated by the Form
          * Editor.
          */
         @SuppressWarnings("unchecked")
         // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
         private void initComponents() {

                  jLabel1 = new javax.swing.JLabel();
                  jLabel2 = new javax.swing.JLabel();
                  jButton1 = new javax.swing.JButton();
                  ciudad = new javax.swing.JComboBox<>();
                  barrio = new javax.swing.JComboBox<>();
                  jButton2 = new javax.swing.JButton();

                  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                  jLabel1.setText("ciudad");

                  jLabel2.setText("barrio");

                  jButton1.setText(" ciudadanos que no han sido evaluados");
                  jButton1.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jButton1ActionPerformed(evt);
                           }
                  });

                  ciudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                  ciudad.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    ciudadActionPerformed(evt);
                           }
                  });

                  barrio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                  barrio.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    barrioActionPerformed(evt);
                           }
                  });

                  jButton2.setText("ciudadanos seleccionados como vulnerable");
                  jButton2.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jButton2ActionPerformed(evt);
                           }
                  });

                  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                  getContentPane().setLayout(layout);
                  layout.setHorizontalGroup(
                           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(layout.createSequentialGroup()
                                    .addGap(51, 51, 51)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                             .addGroup(layout.createSequentialGroup()
                                                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                               .addComponent(jLabel1)
                                                               .addComponent(jLabel2))
                                                      .addGap(45, 45, 45)
                                                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                               .addComponent(ciudad, 0, 270, Short.MAX_VALUE)
                                                               .addComponent(barrio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                      .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                             .addGroup(layout.createSequentialGroup()
                                                      .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                                                      .addGap(18, 18, 18)
                                                      .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addGap(27, 27, 27))))
                  );
                  layout.setVerticalGroup(
                           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(layout.createSequentialGroup()
                                    .addGap(62, 62, 62)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                             .addComponent(jLabel1)
                                             .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                             .addComponent(jLabel2)
                                             .addComponent(barrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(58, 58, 58)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                             .addComponent(jButton1)
                                             .addComponent(jButton2))
                                    .addContainerGap(78, Short.MAX_VALUE))
                  );

                  pack();
         }// </editor-fold>//GEN-END:initComponents

         private void barrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barrioActionPerformed
                  // TODO add your handling code here:


         }//GEN-LAST:event_barrioActionPerformed

         private void ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadActionPerformed
                  // TODO add your handling code here:

                  if (ciudad.getSelectedIndex() != -1) {
                           control.fillCombo(barrio, "select barrio from v_barrio where ciudad='" + ciudad.getSelectedItem().toString() + "'");

                  }
         }//GEN-LAST:event_ciudadActionPerformed

         private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                  // TODO add your handling code here:

                  if (barrio.getSelectedIndex() != -1) {
                           String ba = barrio.getSelectedItem().toString();

                           HashMap parametros = new HashMap<>();
                           parametros.put("barrio", ba);
                           JasperViewer reporte = control.showReport("reporte/barrio_1.jasper", parametros);
                           try {
                                    reporte.setTitle("mostrando ciudadanos vulnerables por barrio");
                           } catch (Exception e) {
                           }
                  } else {
                           JOptionPane.showMessageDialog(null, "seleccione el barrio");
                  }
         }//GEN-LAST:event_jButton2ActionPerformed

         private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                  // TODO add your handling code here:
                  if (barrio.getSelectedIndex() != -1) {
                           String ba = barrio.getSelectedItem().toString();

                           HashMap parametros = new HashMap<>();
                           parametros.put("barrio", ba);
                           JasperViewer reporte = control.showReport("reporte/barrio.jasper", parametros);
                           try {
                                    reporte.setTitle("mostrando los ciudadanos que faltan evaluar por barrios");
                           } catch (Exception e) {
                           }
                  } else {
                           JOptionPane.showMessageDialog(null, "seleccione el barrio");
                  }
         }//GEN-LAST:event_jButton1ActionPerformed

         /**
          * @param args the command line arguments
          */
         public static void main(String args[]) {
                  /* Set the Nimbus look and feel */
                  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                  /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                   */
                  try {
                           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                    if ("Nimbus".equals(info.getName())) {
                                             javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                             break;
                                    }
                           }
                  } catch (ClassNotFoundException ex) {
                           java.util.logging.Logger.getLogger(reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  } catch (InstantiationException ex) {
                           java.util.logging.Logger.getLogger(reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  } catch (IllegalAccessException ex) {
                           java.util.logging.Logger.getLogger(reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                           java.util.logging.Logger.getLogger(reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  }
                  //</editor-fold>

                  /* Create and display the form */
                  java.awt.EventQueue.invokeLater(new Runnable() {
                           public void run() {
                                    new reporte().setVisible(true);
                           }
                  });
         }

         // Variables declaration - do not modify//GEN-BEGIN:variables
         private javax.swing.JComboBox<String> barrio;
         private javax.swing.JComboBox<String> ciudad;
         private javax.swing.JButton jButton1;
         private javax.swing.JButton jButton2;
         private javax.swing.JLabel jLabel1;
         private javax.swing.JLabel jLabel2;
         // End of variables declaration//GEN-END:variables
}
